FROM alpine:3.20
RUN apk add --no-cache pgbouncer dumb-init
COPY pgbouncer.ini /etc/pgbouncer/pgbouncer.ini
COPY userlist.txt   /etc/pgbouncer/userlist.txt
EXPOSE 6432
ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["pgbouncer","/etc/pgbouncer/pgbouncer.ini"]
