global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s
  external_labels:
    env: dev

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:4001
          - records-service:4002
          - listings-service:4003
          - analytics-service:4004
          - api-gateway:4000
          - python-ai-service:5005

  # Optional NGINX exporter (only if you actually run one)
  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # CORRECT: scrape the exporter, not haproxy:8404 directly
  - job_name: haproxy
    static_configs:
      - targets: ["haproxy-exporter:9101"]