global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "node-services"
    static_configs:
      - targets:
          - auth-service:4001
          - records-service:4002
          - listings-service:4003
          - analytics-service:4004
          - api-gateway:4000
          - python-ai-service:5005
