#!/usr/bin/env python3
"""Stage-2: compare extracted staging tree to repo; emit BUNDLE_ANALYSIS_*.md."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from bundle_audit_lib import (
    classify_path,
    detect_strip_prefix,
    disk_regular_files_sorted,
    resolve_repo_relative,
    strip_prefix,
)


def file_sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def walk_staging_files(staging: Path) -> list[str]:
    """Aligned with Protocol v1 disk manifest (AppleDouble-neutral, no MANIFEST.sha256)."""
    return disk_regular_files_sorted(staging)


def detect_strip_from_staging(rels: list[str]) -> str:
    return detect_strip_prefix(rels)


def analyze(staging: Path, repo: Path, tarball: Path | None) -> dict:
    staging = staging.resolve()
    repo = repo.resolve()
    rels = walk_staging_files(staging)
    strip_p = detect_strip_from_staging(rels)

    rows: list[dict] = []
    stats = Counter()
    by_bucket: dict[str, list[str]] = defaultdict(list)

    for rel in sorted(set(rels)):
        logical = strip_prefix(rel, strip_p)
        if logical == ".":
            continue
        bucket = classify_path(logical)
        spath = staging / rel
        rpath = repo / resolve_repo_relative(logical)
        note = ""
        if not rpath.exists():
            parity = "missing_in_repo"
        elif rpath.is_dir():
            parity = "repo_is_dir"
        elif spath.is_file() and rpath.is_file():
            try:
                hs, hr = file_sha256(spath), file_sha256(rpath)
                parity = "identical" if hs == hr else "content_diff"
                if parity == "content_diff":
                    note = f"sha256 staging={hs[:12]}… repo={hr[:12]}…"
            except OSError as e:
                parity = "read_error"
                note = str(e)
        else:
            parity = "type_mismatch"

        stats[parity] += 1
        by_bucket[bucket].append(f"{logical} [{parity}]")

        rows.append(
            {
                "logical_path": logical,
                "parity": parity,
                "bucket": bucket,
                "note": note,
            }
        )

    return {
        "staging": str(staging),
        "repo": str(repo),
        "tarball": str(tarball) if tarball else None,
        "strip_prefix": strip_p.rstrip("/") or None,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "file_count": len(rels),
        "stats": dict(stats),
        "rows": rows,
        "by_bucket": {k: v[:80] for k, v in sorted(by_bucket.items(), key=lambda x: x[0])},
    }


def render_markdown(data: dict, archive_stem: str) -> str:
    lines = [
        f"# Bundle analysis: `{archive_stem}`",
        "",
        "Generated by `tools/bundle-audit/bundle_ingestion_analyze.py` (controlled ingestion; repo is canonical).",
        "",
        "## Metadata",
        "",
        f"- **Staging tree:** `{data['staging']}`",
        f"- **Repo root:** `{data['repo']}`",
        f"- **Source tarball:** `{data.get('tarball') or '(unknown)'}`",
        f"- **Detected strip prefix:** `{data.get('strip_prefix') or '(none)'}`",
        f"- **Files under staging (after skips):** {data['file_count']}",
        f"- **UTC timestamp:** {data['generated_at']}",
        "",
        "## Parity summary",
        "",
        "| Class | Count |",
        "|-------|------:|",
    ]
    for k, v in sorted(data["stats"].items(), key=lambda x: -x[1]):
        lines.append(f"| `{k}` | {v} |")
    lines += [
        "",
        "## Classification (sample per bucket)",
        "",
    ]
    for bucket, samples in sorted(data["by_bucket"].items()):
        lines.append(f"### `{bucket}`")
        lines.append("")
        for s in samples[:40]:
            lines.append(f"- `{s}`")
        if len(samples) > 40:
            lines.append(f"- … *{len(samples) - 40} more*")
        lines.append("")

    lines += [
        "## Safe import suggestions",
        "",
        "- Paths marked **`missing_in_repo`** may be candidates for **add-if-missing** imports; review namespace/SNI (`record-platform`, `record.test`, `kafka-ssl-secret`).",
        "- Paths marked **`content_diff`** require **manual diff** (`diff -u` or IDE); do not `cp -r` from staging.",
        "- Prefer **`git apply`** / focused **`git checkout -- path`** over wholesale copy.",
        "- **Do not** overwrite `scripts/run-preflight-scale-and-all-suites.sh` from bundles unless explicitly approved.",
        "",
        "## Top paths to review",
        "",
    ]
    interesting = [r for r in data["rows"] if r["parity"] in ("missing_in_repo", "content_diff")]
    interesting.sort(key=lambda r: (r["parity"], r["bucket"], r["logical_path"]))
    for r in interesting[:150]:
        lines.append(f"- `{r['logical_path']}` — **{r['parity']}** ({r['bucket']}) {r['note']}".rstrip())
    if len(interesting) > 150:
        lines.append(f"- … *{len(interesting) - 150} more missing/diff rows*")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--staging", type=Path, required=True, help="Extracted staging directory")
    ap.add_argument("--repo", type=Path, required=True, help="Record platform repo root")
    ap.add_argument("--output", type=Path, required=True, help="Markdown report path")
    ap.add_argument("--tarball", type=Path, default=None, help="Original archive (provenance)")
    ap.add_argument("--json", type=Path, default=None, help="Optional machine-readable JSON path")
    args = ap.parse_args()

    stem = args.staging.name
    data = analyze(args.staging, args.repo, args.tarball)
    md = render_markdown(data, stem)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(md, encoding="utf-8")
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"Wrote {args.output}")
    if args.json:
        print(f"Wrote {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
