apiVersion: v1
kind: Service
metadata:
  name: auction-monitor
  namespace: record-platform
  labels: { app: auction-monitor }
spec:
  selector: { app: auction-monitor }
  ports:
    - name: http
      port: 4008
      targetPort: http
    - name: grpc
      port: 50059
      targetPort: grpc