all:
  children:
    kubernetes:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          kubeconfig_path: "~/.kube/config"
          kubeconfig_context: null  # Use current context

