#!/usr/bin/env bash
# Write preflight summary to bench_logs/PREFLIGHT_SUMMARY_<timestamp>.md (and PREFLIGHT_SUMMARY.md).
# Includes: pgbench TPS/latency per DB (piped from logs), EXPLAIN (ANALYZE) for all schemas/DBs, k6 phase logs, observation deck status.
# Usage: PGBENCH_LOG_DIR=/tmp/pgbench-... [EXPLAIN_DIR=bench_logs/explain-all-...] [SUITE_LOG_DIR=/tmp/suite-logs-...] ./scripts/write-preflight-summary-md.sh

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

TS=$(date +%Y%m%d-%H%M%S)
BENCH_LOGS="${BENCH_LOGS:-$REPO_ROOT/bench_logs}"
mkdir -p "$BENCH_LOGS"
OUT_MD="$BENCH_LOGS/PREFLIGHT_SUMMARY_$TS.md"
OUT_LATEST="$BENCH_LOGS/PREFLIGHT_SUMMARY.md"

PGBENCH_LOG_DIR="${PGBENCH_LOG_DIR:-}"
EXPLAIN_DIR="${EXPLAIN_DIR:-}"
SUITE_LOG_DIR="${SUITE_LOG_DIR:-}"

# Latest explain-all-* if not set
if [[ -z "$EXPLAIN_DIR" ]] && [[ -d "$BENCH_LOGS" ]]; then
  EXPLAIN_DIR=$(find "$BENCH_LOGS" -maxdepth 1 -type d -name 'explain-all-*' 2>/dev/null | sort -r | head -1)
fi

# Observation deck status (Istio, Splunk, Grafana, Prometheus, New Relic, Linkerd, Jaeger, OpenTelemetry + sidecars)
OBS_OUT=""
if [[ -f "$SCRIPT_DIR/check-observability-deck.sh" ]]; then
  chmod +x "$SCRIPT_DIR/check-observability-deck.sh" 2>/dev/null || true
  OBS_OUT=$("$SCRIPT_DIR/check-observability-deck.sh" 2>/dev/null || echo "(check-observability-deck.sh failed)")
fi

{
  echo "# Preflight summary — $TS"
  echo ""
  echo "Generated by \`write-preflight-summary-md.sh\` after pgbench + tuning. Explains what ran and what the results are."
  echo ""
  echo "---"
  echo ""
  echo "## 1. pgbench (all 8 DBs) — TPS, latency, errors"
  echo ""
  if [[ -n "$PGBENCH_LOG_DIR" ]] && [[ -d "$PGBENCH_LOG_DIR" ]]; then
    for name in records social auth shopping listings analytics auction_monitor python_ai; do
      log="$PGBENCH_LOG_DIR/$name.log"
      if [[ -f "$log" ]]; then
        tps=$(grep -o 'tps = [0-9.]*' "$log" 2>/dev/null | tail -1 || echo "N/A")
        lat=$(grep -o 'latency average = [0-9.]* ms' "$log" 2>/dev/null | tail -1 || echo "")
        stddev=$(grep -o 'latency stddev = [0-9.]* ms' "$log" 2>/dev/null | tail -1 || echo "")
        trans=$(grep -o 'number of transactions actually processed: [0-9]*' "$log" 2>/dev/null | tail -1 || echo "")
        echo "### $name"
        echo "- **TPS**: $tps"
        echo "- **Latency**: $lat $stddev"
        [[ -n "$trans" ]] && echo "- $trans"
        echo ""
      else
        echo "- **$name**: (no log)"
        echo ""
      fi
    done
    echo "Logs: \`$PGBENCH_LOG_DIR/*.log\`"
  else
    echo "No pgbench log dir set (PGBENCH_LOG_DIR)."
  fi
  echo ""
  echo "---"
  echo ""
  echo "## 2. EXPLAIN (ANALYZE, BUFFERS) — all DBs/schemas"
  echo ""
  if [[ -n "$EXPLAIN_DIR" ]] && [[ -d "$EXPLAIN_DIR" ]]; then
    echo "Output directory: \`$EXPLAIN_DIR\`"
    echo ""
    for f in records.txt records-count.txt social-forum.txt social-messages.txt listings.txt shopping.txt auth.txt auction-monitor.txt analytics.txt python-ai.txt bottleneck-summary.txt; do
      if [[ -f "$EXPLAIN_DIR/$f" ]]; then
        echo "### \`$f\`"
        echo ""
        echo "\`\`\`"
        head -30 "$EXPLAIN_DIR/$f" 2>/dev/null
        echo "\`\`\`"
        echo ""
      fi
    done
  else
    echo "No EXPLAIN directory (EXPLAIN_DIR or latest bench_logs/explain-all-*)."
  fi
  echo "---"
  echo ""
  echo "## 3. k6 load phases (read, soak, sweep, limit, max, http3)"
  echo ""
  if [[ -n "$SUITE_LOG_DIR" ]] && [[ -d "$SUITE_LOG_DIR" ]]; then
    for phase in read soak sweep limit max http3 load; do
      [[ -f "$SUITE_LOG_DIR/k6-$phase.log" ]] && echo "- \`k6-$phase.log\`"
    done
    [[ -z "$(ls -A "$SUITE_LOG_DIR"/k6-*.log 2>/dev/null)" ]] && echo "k6 logs: \`$SUITE_LOG_DIR/k6-*.log\` (if RUN_K6=1 and K6_PHASES set)."
  else
    echo "Suite log dir not set; k6 logs are under the directory passed to run-all-test-suites (e.g. bench_logs/suite-logs-* or /tmp/suite-logs-*)."
  fi
  echo ""
  echo "---"
  echo ""
  echo "## 4. Observation deck (traffic capture + stack)"
  echo ""
  echo "Ensure sidecars and stack are running so load/suite traffic is captured: Istio, Splunk, Grafana, Prometheus, New Relic, Linkerd, Jaeger, OpenTelemetry."
  echo ""
  if [[ -n "$OBS_OUT" ]]; then
    echo "\`\`\`"
    echo "$OBS_OUT" | sed 's/^/  /'
    echo "\`\`\`"
  else
    echo "Run \`./scripts/check-observability-deck.sh\` for current status."
  fi
  echo ""
  echo "---"
  echo ""
  echo "## 5. Next steps"
  echo ""
  echo "- Review EXPLAIN plans in \`$EXPLAIN_DIR\` (target execution time ≤20 ms)."
  echo "- Run \`RUN_QUICK_PGBENCH=1\` for a fast latency check, or full preflight with \`RUN_FULL_LOAD=1\` for pgbench + k6 + suites."
  echo "- Single command: \`COLIMA_START=1 RUN_FULL_LOAD=1 KILL_STALE_FIRST=1 PGBENCH_PARALLEL=1 ./scripts/run-preflight-scale-and-all-suites.sh\` (sets SUITE_LOG_DIR, K6_CA_ABSOLUTE, K6_PHASES, K6_HTTP3)."
  echo "- Little's Law / percentiles: see \`scripts/load/LOAD_TESTS_CATALOG.md\` and k6 \`handleSummary\` / \`calculate-granular-percentiles.js\`."
  echo "- Dashboard (D3.js + GraphQL): Observation deck UI at \`/observation-deck\` in the webapp; API \`/api/observation-deck/data\` for preflight/pgbench/k6 data."
} > "$OUT_MD"
cp -f "$OUT_MD" "$OUT_LATEST"

# JSON for observation-deck dashboard (D3/GraphQL)
OUT_JSON="$BENCH_LOGS/preflight-results.json"
pgbench_json="[]"
PGBENCH_LOG="${PGBENCH_LOG:-}"

extract_one() {
  local block="$1"
  local tps lat stddev trans
  tps=$(echo "$block" | grep -o 'tps = [0-9.]*' 2>/dev/null | tail -1 | grep -oE '[0-9.]+' || echo "")
  lat=$(echo "$block" | grep -o 'latency average = [0-9.]* ms' 2>/dev/null | tail -1 | grep -oE '[0-9.]+' || echo "")
  stddev=$(echo "$block" | grep -o 'latency stddev = [0-9.]* ms' 2>/dev/null | tail -1 | grep -oE '[0-9.]+' || echo "")
  trans=$(echo "$block" | grep -o 'number of transactions actually processed: [0-9]*' 2>/dev/null | tail -1 | grep -oE '[0-9]+' || echo "")
  echo "${tps:-} ${lat:-} ${stddev:-} ${trans:-}"
}

if [[ -n "$PGBENCH_LOG_DIR" ]] && [[ -d "$PGBENCH_LOG_DIR" ]]; then
  pgbench_json="["
  first=1
  for name in records social auth shopping listings analytics auction_monitor python_ai; do
    log="$PGBENCH_LOG_DIR/$name.log"
    tps=""; lat=""; stddev=""; trans=""
    if [[ -f "$log" ]]; then
      read -r tps lat stddev trans <<< "$(extract_one "$(cat "$log")")"
    fi
    [[ $first -eq 0 ]] && pgbench_json+=","
    first=0
    pgbench_json+="{\"db\":\"$name\",\"tps\":${tps:-null},\"latency_ms\":${lat:-null},\"latency_stddev_ms\":${stddev:-null},\"transactions\":${trans:-null}}"
  done
  pgbench_json+="]"
elif [[ -n "$PGBENCH_LOG" ]] && [[ -f "$PGBENCH_LOG" ]]; then
  # Parse combined preflight log (order: records, social, auth, shopping, listings, analytics, auction_monitor, python_ai)
  names=(records social auth shopping listings analytics auction_monitor python_ai)
  blocks=()
  current=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*(Records[[:space:]]+DB|run_.*pgbench_sweep) ]]; then
      [[ -n "$current" ]] && blocks+=("$current")
      current="$line"
    else
      [[ -n "$current" ]] && current+=$'\n'
      current+="$line"
    fi
  done < "$PGBENCH_LOG"
  [[ -n "$current" ]] && blocks+=("$current")
  pgbench_json="["
  for i in "${!names[@]}"; do
    name="${names[$i]}"
    tps=""; lat=""; stddev=""; trans=""
    if [[ -n "${blocks[$i]:-}" ]]; then
      read -r tps lat stddev trans <<< "$(extract_one "${blocks[$i]}")"
    fi
    [[ $i -gt 0 ]] && pgbench_json+=","
    pgbench_json+="{\"db\":\"$name\",\"tps\":${tps:-null},\"latency_ms\":${lat:-null},\"latency_stddev_ms\":${stddev:-null},\"transactions\":${trans:-null}}"
  done
  pgbench_json+="]"
fi
k6_logs="[]"
if [[ -n "$SUITE_LOG_DIR" ]] && [[ -d "$SUITE_LOG_DIR" ]]; then
  k6_logs="["
  first=1
  for phase in read soak sweep limit max http3 load; do
    [[ -f "$SUITE_LOG_DIR/k6-$phase.log" ]] || continue
    [[ $first -eq 0 ]] && k6_logs+=","
    first=0
    k6_logs+="\"k6-$phase.log\""
  done
  k6_logs+="]"
fi
# Optional: k6 protocol comparison (HTTP/2 vs HTTP/3)
protocol_comparison="null"
if [[ -n "$SUITE_LOG_DIR" ]] && [[ -f "$SUITE_LOG_DIR/protocol-comparison.json" ]]; then
  protocol_comparison=$(cat "$SUITE_LOG_DIR/protocol-comparison.json" 2>/dev/null || echo "null")
fi

printf '%s\n' "{
  \"generated_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
  \"preflight_summary_md\": \"$OUT_LATEST\",
  \"pgbench\": $pgbench_json,
  \"explain_dir\": \"${EXPLAIN_DIR:-}\",
  \"suite_log_dir\": \"${SUITE_LOG_DIR:-}\",
  \"k6_logs\": $k6_logs,
  \"protocol_comparison\": $protocol_comparison,
  \"observation_deck_summary\": $(echo "$OBS_OUT" | jq -R -s . 2>/dev/null || echo "\"\"")
}" > "$OUT_JSON"
echo "✅ Preflight summary: $OUT_MD (and $OUT_LATEST); JSON: $OUT_JSON"
