apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: record-platform
  labels: { app: shopping-service }
spec:
  selector: { app: shopping-service }
  ports:
    - name: http
      port: 4007
      targetPort: 4007
    - name: grpc
      port: 50058
      targetPort: 50058
